// <auto-generated />
using EtüAkademiContext.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace WebProject.Migrations
{
    [DbContext(typeof(EtuAkademiContext))]
    partial class EtuAkademiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("WebProject.Models.Bolum", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("BolumAdı")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Bolumno")
                        .HasColumnType("int");

                    b.Property<string>("Rutbe")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Bolum");
                });

            modelBuilder.Entity("WebProject.Models.Person", b =>
                {
                    b.Property<int>("AkademisyenNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("AdSoyad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArastirmaAlanı")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BolumNo")
                        .HasColumnType("int");

                    b.Property<string>("Doktora")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Eposta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hakkında")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResimUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelefonNUmarası")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YüksekLisans")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lisans")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AkademisyenNo");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("WebProject.Models.Project", b =>
                {
                    b.Property<int>("ProjeNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("ProjeHakkında")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjeIsmi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjeNe")
                        .HasColumnType("int");

                    b.Property<string>("ResimUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProjeNo");

                    b.ToTable("Project");
                });
#pragma warning restore 612, 618
        }
    }
}
